# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"

include:
    [extra]

exclude:
  - "*/*~"
  - "*/.#*"
  - README.md
  - LICENSE
  - src
  - Gemfile
  - Gemfile.lock

highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
disqus:      mbrjnt
comments:    true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: MBR
      comments:    true
      hide:        false
      plotly:      false
      noTeX:       false
      bootstrap_ver: 4
      mathjax_version: 4.3.1
      

description:  blog-a-like

author:
  name:      Marc B. Reynolds
  email:     marc.b.reynolds@gmail.com
  github:    Marc-B-Reynolds
  linkedin:
  bio:       jack of no trades
  
lsi:	     false
safe:	     true
incremental: false
gist:
noscript:	false

twitter:
 username: marc_b_reynolds
 card:     summary

sass:
  style: compressed

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
# - jekyll-feed      # doing manually
  
plugins_dir:
  - jekyll-mentions
  - jekyll-paginate

google_analytics: UA-77902817-1

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
copyright_path: copyright.html

BASE_PATH:
